model:
  name: UNet
  n_classes: 20
dataset:
  name: VOCSegmentationDataLoader
  root: data
  year: "2012"
  download: True
  batch_size: 4
train:
  epochs: 5
  optimizer:
    name: SGD
    lr: 1e-3
  lr_scheduler:
    name: ExponentialLR
    gamma: 0.95